project:
  type: book
  output-dir: docs

book:
  title: "TU Delft Thesis Template"
  search: true
  repo-url: https://github.com/piistis-tudelft/quarto-thesis-template
  repo-actions: [edit]
  downloads: [pdf, epub]
  author:
    - name: Patrick Altmeyer
      affiliations:
        - name: Delft University of Technology
          department: EEMCS
          id: 1
      email: p.altmeyer@tudelft.nl
      url: https://www.patalt.org/
    - name: Andrew Demetriou
      affiliations:
        - ref: 1
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  tudelft-pdf:
    keep-tex: true
  html:
    theme:
      - cosmo
      - brand
  epub: default



